name: E2E on Edge

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          project: ./
          browser: edge
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3000"
